import 'package:chatti/entities/word.dart';

 List<Word> wordsA1 = [
  Word(word: "Ich", pluralForm: "", type: Word.PRONOUN, examples: ["Ich esse eine Banane"], translation: {Word.FRENCH:"Je"}, language: Word.FRENCH),
  Word(word: "deutsch", pluralForm: "", type: Word.ADJECTIVE, examples: [""], translation: {Word.FRENCH:"allemand"}, language: Word.FRENCH),
  Word(word: "heissen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"s'appeler"}, language: Word.FRENCH),
  Word(word: "hören", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"écouter"}, language: Word.FRENCH),
  Word(word: "kennen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"connaître"}, language: Word.FRENCH),
  Word(word: "das Lied", pluralForm: "die Lieder", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la chanson"}, language: Word.FRENCH),
  Word(word: "der Name", pluralForm: "die Namen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le nom"}, language: Word.FRENCH),
  Word(word: "noch", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"encore"}, language: Word.FRENCH),
  Word(word: "welch-", pluralForm: "", type: Word.UNKNOWN, examples: ["Welches Lied hörst du oft ?"], translation: {Word.FRENCH:"quelles, quels"}, language: Word.FRENCH),
  Word(word: "wie", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"comment"}, language: Word.FRENCH),
  Word(word: "ankreuzen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"cocher"}, language: Word.FRENCH),
  Word(word: "die", pluralForm: "", type: Word.ARTICLE, examples: [""], translation: {Word.FRENCH:"les"}, language: Word.FRENCH),
  Word(word: "du", pluralForm: "", type: Word.PRONOUN, examples: [""], translation: {Word.FRENCH:"tu"}, language: Word.FRENCH),
  Word(word: "ein/e", pluralForm: "", type: Word.ARTICLE, examples: [""], translation: {Word.FRENCH:"un/e"}, language: Word.FRENCH),
  Word(word: "hallo", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"bonjour, salut"}, language: Word.FRENCH),
  Word(word: "das Kettenspiel", pluralForm: "die Kettenspiele", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le jeu en chaîne"}, language: Word.FRENCH),
  Word(word: "meist-", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"le plus de"}, language: Word.FRENCH),
  Word(word: "notieren", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"noter"}, language: Word.FRENCH),
  Word(word: "sein", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"être"}, language: Word.FRENCH),
  Word(word: "der Sitzplan", pluralForm: "die Sitzpläne", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le plan de la classe"}, language: Word.FRENCH),
  Word(word: "sprechen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"parler"}, language: Word.FRENCH),
  Word(word: "und", pluralForm: "", type: Word.CONNECTOR, examples: [""], translation: {Word.FRENCH:"et"}, language: Word.FRENCH),
  Word(word: "wer", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"qui"}, language: Word.FRENCH),
  Word(word: "wissen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"savoir"}, language: Word.FRENCH),
  Word(word: "zeichnen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"dessiner"}, language: Word.FRENCH),
  Word(word: "auf Wiedersehen", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"au revoir"}, language: Word.FRENCH),
  Word(word: "guten Abend", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"bonsoir"}, language: Word.FRENCH),
  Word(word: "gute Nacht", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"bonne nuit"}, language: Word.FRENCH),
  Word(word: "guten Morgen", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"bonjour(le matin)"}, language: Word.FRENCH),
  Word(word: "guten Tag", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"bonjour"}, language: Word.FRENCH),
  Word(word: "ergänzen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"compléter"}, language: Word.FRENCH),
  Word(word: "(das) Deutschland", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'Allemagne"}, language: Word.FRENCH),
  Word(word: "das Gespräch", pluralForm: "die Gespräche", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le dialogue"}, language: Word.FRENCH),
  Word(word: "(der) Iran", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'Iran"}, language: Word.FRENCH),
  Word(word: "(das) Mexiko", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le Mexique"}, language: Word.FRENCH),
  Word(word: "mit", pluralForm: "", type: Word.PREPOSITION, examples: [""], translation: {Word.FRENCH:"avec"}, language: Word.FRENCH),
  Word(word: "nein", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"non"}, language: Word.FRENCH),
  Word(word: "(das) Österreich", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'Autriche"}, language: Word.FRENCH),
  Word(word: "sagen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"dire"}, language: Word.FRENCH),
  Word(word: "(die) Schweiz", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la Suisse"}, language: Word.FRENCH),
  Word(word: "(die) Türkei", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la Turquie"}, language: Word.FRENCH),
  Word(word: "vergleichen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"comparer"}, language: Word.FRENCH),
  Word(word: "was", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"quoi"}, language: Word.FRENCH),
  Word(word: "weiterhören", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"écouter la suite"}, language: Word.FRENCH),
  Word(word: "zuordnen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"associer"}, language: Word.FRENCH),
  Word(word: "die(Sg)", pluralForm: "", type: Word.ARTICLE, examples: [""], translation: {Word.FRENCH:"la"}, language: Word.FRENCH),
  Word(word: "das Frankreich", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la France"}, language: Word.FRENCH),
  Word(word: "die Musik", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la musique"}, language: Word.FRENCH),
  Word(word: "auch", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"aussi"}, language: Word.FRENCH),
  Word(word: "danke", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"merci"}, language: Word.FRENCH),
  Word(word: "die Frau", pluralForm: "die Frauen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la femme"}, language: Word.FRENCH),
  Word(word: "gut", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"bien"}, language: Word.FRENCH),
  Word(word: "der Herr", pluralForm: "die Herren", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le monsieur"}, language: Word.FRENCH),
  Word(word: "Ihnen", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"vous(vouvoiement)"}, language: Word.FRENCH),
  Word(word: "der Tag", pluralForm: "die Tage", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le jour"}, language: Word.FRENCH),
  Word(word: "(das) Ägypten", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'égypte"}, language: Word.FRENCH),
  Word(word: "antworten", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"répondre"}, language: Word.FRENCH),
  Word(word: "arbeiten", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"travailler"}, language: Word.FRENCH),
  Word(word: "auf", pluralForm: "", type: Word.PREPOSITION, examples: [""], translation: {Word.FRENCH:"sur, à"}, language: Word.FRENCH),
  Word(word: "bekannt", pluralForm: "", type: Word.ADJECTIVE, examples: [""], translation: {Word.FRENCH:"connu"}, language: Word.FRENCH),
  Word(word: "der Familienname", pluralForm: "die Familiennamen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le nom de famille"}, language: Word.FRENCH),
  Word(word: "fehlend", pluralForm: "", type: Word.ADJECTIVE, examples: [""], translation: {Word.FRENCH:"manquant"}, language: Word.FRENCH),
  Word(word: "formell", pluralForm: "", type: Word.ADJECTIVE, examples: [""], translation: {Word.FRENCH:"officiel"}, language: Word.FRENCH),
  Word(word: "(das) Grossbritannien", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la Grande Bretagne"}, language: Word.FRENCH),
  Word(word: "Ihr(e)", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"Votre, vos"}, language: Word.FRENCH),
  Word(word: "(das) Indien", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'Inde"}, language: Word.FRENCH),
  Word(word: "die Information", pluralForm: "die Informationen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'information"}, language: Word.FRENCH),
  Word(word: "informell", pluralForm: "", type: Word.ADJECTIVE, examples: [""], translation: {Word.FRENCH:"informel"}, language: Word.FRENCH),
  Word(word: "ja", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"oui"}, language: Word.FRENCH),
  Word(word: "noch einmal", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"encore une fois"}, language: Word.FRENCH),
  Word(word: "order", pluralForm: "", type: Word.CONNECTOR, examples: [""], translation: {Word.FRENCH:"ou"}, language: Word.FRENCH),
  Word(word: "der Partner", pluralForm: "die Partner", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le partenaire"}, language: Word.FRENCH),
  Word(word: "die Persönlichkeit", pluralForm: "die Persönlichkeiten", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la personnalité"}, language: Word.FRENCH),
  Word(word: "die Seite", pluralForm: "die Seiten", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la page"}, language: Word.FRENCH),
  Word(word: "sie(Sg)", pluralForm: "", type: Word.PRONOUN, examples: [""], translation: {Word.FRENCH:"elle"}, language: Word.FRENCH),
  Word(word: "üben", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"s'entraîner"}, language: Word.FRENCH),
  Word(word: "der Vorname", pluralForm: "die Vornamen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le prénom"}, language: Word.FRENCH),
  Word(word: "würfeln", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"jeter un dé"}, language: Word.FRENCH),
  Word(word: "dir", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"toi,tu"}, language: Word.FRENCH),
  Word(word: "nicht", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"pas"}, language: Word.FRENCH),
  Word(word: "die Person", pluralForm: "die Personen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la personne"}, language: Word.FRENCH),
  Word(word: "sehr", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"très"}, language: Word.FRENCH),
  Word(word: "so", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"si"}, language: Word.FRENCH),
  Word(word: "die Konferenz", pluralForm: "die Konferenzen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la conférence"}, language: Word.FRENCH),
  Word(word: "das Namensschild", pluralForm: "die Namensschilder", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le badge"}, language: Word.FRENCH),
  Word(word: "die Party", pluralForm: "die Partys", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la fête, la soirée"}, language: Word.FRENCH),
  Word(word: "schreiben", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"écrire"}, language: Word.FRENCH),
  Word(word: "bitte", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"s'il vous plaît"}, language: Word.FRENCH),
  Word(word: "buchstabieren", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"épeler"}, language: Word.FRENCH),
  Word(word: "diktieren", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"dicter"}, language: Word.FRENCH),
  Word(word: "mein(e)", pluralForm: "", type: Word.PRONOUN, examples: [""], translation: {Word.FRENCH:"mon, ma, mes"}, language: Word.FRENCH),
  Word(word: "nachsprechen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"répeter"}, language: Word.FRENCH),
  Word(word: "der Umlaut", pluralForm: "die Umlaute", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la voyelle infléchie(¨)"}, language: Word.FRENCH),
  Word(word: "der Abschied", pluralForm: "die Abschiede", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la prise de congé"}, language: Word.FRENCH),
  Word(word: "die Begrüssung", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la salutation"}, language: Word.FRENCH),
  Word(word: "das Bildlexikon", pluralForm: "die Bildlexika", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le dictionnaire en images"}, language: Word.FRENCH),
  Word(word: "der Abend", pluralForm: "die Abende", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le soir"}, language: Word.FRENCH),
  Word(word: "der Morgen", pluralForm: "die Morgen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le matin"}, language: Word.FRENCH),
  Word(word: "die Nacht", pluralForm: "die Nächte", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la nuit"}, language: Word.FRENCH),
  Word(word: "die Wendung", pluralForm: "die Wendungen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'expression"}, language: Word.FRENCH),
  Word(word: "das Ende", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la fin"}, language: Word.FRENCH),
  Word(word: "die Stunde", pluralForm: "die Stunden", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'heure"}, language: Word.FRENCH),
  Word(word: "die Aussage", pluralForm: "die Aussagen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'assertion"}, language: Word.FRENCH),
  Word(word: "die Herkunft", pluralForm: "die Herkünfte", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'origine"}, language: Word.FRENCH),
  Word(word: "die Kommunikation", pluralForm: "die Kommunikationen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la communication"}, language: Word.FRENCH),
  Word(word: "die Position", pluralForm: "die Positionen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la position"}, language: Word.FRENCH),
  Word(word: "das Sprechtraining", pluralForm: "die Sprechtrainings", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'entrainement à la prononciation"}, language: Word.FRENCH),
  Word(word: "das Verb", pluralForm: "die Verben", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le verbe"}, language: Word.FRENCH),
  Word(word: "die Wiederholung", pluralForm: "die Wiederholungen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la répétition"}, language: Word.FRENCH),
  Word(word: "bitten um", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"demander(de faire qqch)"}, language: Word.FRENCH),
  Word(word: "das Alphabet", pluralForm: "die Alphabete", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'alphabet"}, language: Word.FRENCH),
  Word(word: "ander", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"autre"}, language: Word.FRENCH),
  Word(word: "aus", pluralForm: "", type: Word.PREPOSITION, examples: [""], translation: {Word.FRENCH:"de(provenance)"}, language: Word.FRENCH),
  Word(word: "das Befinden", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'état de santé"}, language: Word.FRENCH),
  Word(word: "sich begrüssen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"se saluer"}, language: Word.FRENCH),
  Word(word: "das", pluralForm: "", type: Word.ARTICLE, examples: [""], translation: {Word.FRENCH:"le/la"}, language: Word.FRENCH),
  Word(word: "er", pluralForm: "", type: Word.PRONOUN, examples: [""], translation: {Word.FRENCH:"il"}, language: Word.FRENCH),
  Word(word: "fragen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"demander"}, language: Word.FRENCH),
  Word(word: "gehen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"aller"}, language: Word.FRENCH),
  Word(word: "die Grammatik", pluralForm: "die Grammatiken", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la grammaire"}, language: Word.FRENCH),
  Word(word: "kommen (aus)", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"venir de"}, language: Word.FRENCH),
  Word(word: "die Konjugation", pluralForm: "die Konjugationen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la conjugaison"}, language: Word.FRENCH),
  Word(word: "das Land", pluralForm: "die Länder", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le pays"}, language: Word.FRENCH),
  Word(word: "der Singular", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le singulier"}, language: Word.FRENCH),
  Word(word: "tschüs", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"au revoir, salut"}, language: Word.FRENCH),
  Word(word: "woher", pluralForm: "", type: Word.UNKNOWN, examples: [""], translation: {Word.FRENCH:"d'où"}, language: Word.FRENCH),
  Word(word: "das Wortfeld", pluralForm: "die Wortfelder", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le champs lexical"}, language: Word.FRENCH),
  Word(word: "ansehen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"regarder"}, language: Word.FRENCH),
];