import 'package:chatti/entities/word.dart';

 List<Word> wordsA2 = [
  Word(word: "die Brezel", pluralForm: "die Brezeln", type: Word.NOUN, examples: ["Ich esse eine Brezel"], translation: {Word.FRENCH:"le bretzel"}, language: Word.FRENCH),
  Word(word: "klappen", pluralForm: "", type: Word.VERB, examples: ["Das klappt Opa!"], translation: {Word.FRENCH:"marcher"}, language: Word.FRENCH),
  Word(word: "kompliziert", pluralForm: "", type: Word.ADJECTIVE, examples: ["Das klappt Opa!"], translation: {Word.FRENCH:"compliqué"}, language: Word.FRENCH),
  Word(word: "der Teig", pluralForm: "die Teige", type: Word.NOUN, examples: ["Wir brauchen auch mehr Teig für die Bretzeln"], translation: {Word.FRENCH:"la pâte"}, language: Word.FRENCH),
  Word(word: "das Studium", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"les études"}, language: Word.FRENCH),
  Word(word: "das Einrad", pluralForm: "die Einräder", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le monocycle"}, language: Word.FRENCH),
  Word(word: "das Fussballbild", pluralForm: "die Fussballbilder", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'image de foot"}, language: Word.FRENCH),
  Word(word: "klettern", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"grimper"}, language: Word.FRENCH),
  Word(word: "übernachten", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"passer la nuit"}, language: Word.FRENCH),
  Word(word: "das Skateboard", pluralForm: "die Skateboards", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le skateboard"}, language: Word.FRENCH),
  Word(word: "", pluralForm: "die Süssigkeiten", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"les sucreries"}, language: Word.FRENCH),
  Word(word: "der Ausschnitt", pluralForm: "die Ausschnitte", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'extrait"}, language: Word.FRENCH),
  Word(word: "der Bäcker", pluralForm: "die Bäcker", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le boulanger"}, language: Word.FRENCH),
  Word(word: "der Cousin", pluralForm: "die Cousins", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le cousin"}, language: Word.FRENCH),
  Word(word: "der Neffe", pluralForm: "die Neffen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le neveu"}, language: Word.FRENCH),
  Word(word: "die Nichte", pluralForm: "die Nichten", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la nièce"}, language: Word.FRENCH),
  Word(word: "der Schwiegersohn", pluralForm: "die Schwiegersöhne", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le gendre"}, language: Word.FRENCH),
  Word(word: "der Schwiegervater", pluralForm: "die Schwiegerväter", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le beau-père"}, language: Word.FRENCH),
  Word(word: "übergeben", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"transmettre"}, language: Word.FRENCH),
  Word(word: "die Zigarette", pluralForm: "die Zigaretten", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la cigarette"}, language: Word.FRENCH),
  Word(word: "verrückt", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"fou"}, language: Word.FRENCH),
  Word(word: "wachsen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"pousser"}, language: Word.FRENCH),
  Word(word: "der Jugendliche", pluralForm: "die Jugendlichen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le jeune"}, language: Word.FRENCH),
  Word(word: "", pluralForm: "die Kindheitserinnerungen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"les souvenirs d'enfance"}, language: Word.FRENCH),
  Word(word: "die Lieblingsdisco", pluralForm: "die Lieblingsdiscos", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la boîte de nuit préférée"}, language: Word.FRENCH),
  Word(word: "die Sekunde", pluralForm: "die Sekunden", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la seconde"}, language: Word.FRENCH),
  Word(word: "das Wahrheitsspiel", pluralForm: "die Wahrheitsspiele", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le jeu de la vérité"}, language: Word.FRENCH),
  Word(word: "aufmachen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"ouvrir"}, language: Word.FRENCH),
  Word(word: "der Schluss", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la fin"}, language: Word.FRENCH),
  Word(word: "die Abstimmung", pluralForm: "die Abstimmungen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le vote"}, language: Word.FRENCH),
  Word(word: "das Ereignis", pluralForm: "die Ereignisse", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'événement"}, language: Word.FRENCH),
  Word(word: "die Familiengeschichte", pluralForm: "", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"l'histoire familiale"}, language: Word.FRENCH),
  Word(word: "streiten", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"se disputer"}, language: Word.FRENCH),
  Word(word: "blöd", pluralForm: "", type: Word.ADJECTIVE, examples: [""], translation: {Word.FRENCH:"idiot"}, language: Word.FRENCH),
  Word(word: "einrichten", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"aménager"}, language: Word.FRENCH),
  Word(word: "renovieren", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"rénover"}, language: Word.FRENCH),
  Word(word: "diskutieren", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"discuter"}, language: Word.FRENCH),
  Word(word: "die Kommode", pluralForm: "die Kommoden", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"la commode"}, language: Word.FRENCH),
  Word(word: "die Wand", pluralForm: "die Wände", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le mur"}, language: Word.FRENCH),
  Word(word: "das Fernsehgerät", pluralForm: "die Fernsehgeräte", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le téléviseur"}, language: Word.FRENCH),
  Word(word: "hängen", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"accrocher"}, language: Word.FRENCH),
  Word(word: "das Kissen", pluralForm: "die Kissen", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le coussin"}, language: Word.FRENCH),
  Word(word: "verstecken", pluralForm: "", type: Word.VERB, examples: [""], translation: {Word.FRENCH:"cacher"}, language: Word.FRENCH),
  Word(word: "die Gemeinsamkeit", pluralForm: "die Gemeinsamkeiten", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le point commun"}, language: Word.FRENCH),
  Word(word: "der Schreibtisch", pluralForm: "die Schreibtische", type: Word.NOUN, examples: [""], translation: {Word.FRENCH:"le bureau"}, language: Word.FRENCH),
];